### ISSUE TITLE
Feature Request: Implement Task Persistence

### ISSUE THREAD

**Issue by ahmedmaaloul** [ahmedmaaloul/Todo_list_application-MAALOUL_Ahmed-CDOF2#3]
**Overview**
Currently, the ToDo List application does not save tasks between sessions. Adding a persistence layer would significantly improve the usability of the app, allowing users to retain their task list even after closing the application.

**Suggested Implementation**
- Research and decide on a suitable method for data persistence (e.g., writing to a file, using a lightweight database).
- Implement the chosen persistence method in the application.
- Ensure that tasks are saved and loaded correctly between sessions.

**Goals**
Enhance the functionality of the ToDo List application by adding the ability to save tasks across sessions, thus increasing its practicality for real-world use.

**Comment by kanyadirichard** [comment]
Hello, I would like to implement the suggested and described feature. Do you consent?
